### ISSUE TITLE
Template validation error: Template format error: Resource name EaaS-VPC is non alphanumeric.

### ISSUE THREAD

**Issue by aheifetz** [OpenWhere/scenery#30]
we need to check Ids in the resource constructors for non alphanumeric char.

ie 

    var vpc = t.vpc('EaaS-VPC').cidrBlock( t.ref('CidrBlock') );

Template validation error: Template format error: Resource name EaaS-VPC is non alphanumeric.

**Comment by owap** [comment]
Okay, so we'll have our constructor validate that the `id` passed in conforms to the regex `[a-zA-Z0-9]` ?  Does it need to start with a letter?
