### ISSUE TITLE
Case sensitive folders

### ISSUE THREAD

**Issue by aheifetz** [OpenWhere/scenery#46]
I'm testing on ubuntu and the folder name is case sensitive which is causing problems in Resources  

 var Instance = require('./EC2/Instance.js');

vs. 

var Instance = require('./ec2/Instance.js');

**Comment by owap** [comment]
Hey Andy,

I can't find any instances in the code of lowercase "ec2" strings. You may
need to modify any old templates you were using.

Can you give me any details about which file this is happening in?

Thanks!
--Andrew

**Comment by owap** [comment]
Oh, make sure you're on the develop branch!
